Desktop version
Abe1able/Personal-Portfolio pull request #7
Opened 2022-08-25 13:36 UTC by Abe1able

### In this commit, I have

- used media queries to make the desktop version of my portfolio.
- used html and css best practices to produce quality code.
- made sure there are no linter errors in my code.

2022-08-25 14:01 UTC, vechicin requested changes
# Hi @Abe1able ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good job matching the template design overall.

## Required Changes ♻️

- [ ] You did not use `display: grid` to lay out your elements in the desktop version. Please make sure you do so as it is a project requirement.
<img width="520" alt="Screen Shot 2022-08-25 at 9 00 43" src="https://user-images.githubusercontent.com/82426682/186685302-0aef80dc-3418-4158-a66c-739be5101332.png">

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 14:01 UTC, vechicin commented on styles.css
> +@media screen and (min-width: 995px) {
You should only have one media query and it should be in the range of 768px. Please fix it.

<img width="892" alt="Screen Shot 2022-08-25 at 8 49 56" src="https://user-images.githubusercontent.com/82426682/186682678-9e16df07-3b58-4a61-8761-a85ac78127ac.png">

2022-08-25 14:01 UTC, vechicin commented on styles.css
>    align-items: center;
Please make sure your design matches the template design.

<img width="1440" alt="Screen Shot 2022-08-25 at 8 52 19" src="https://user-images.githubusercontent.com/82426682/186683268-cb751c7b-7091-4ec8-afcd-922afbc64ffe.png">

<img width="837" alt="Screen Shot 2022-08-25 at 8 52 37" src="https://user-images.githubusercontent.com/82426682/186683349-c0f5fb41-4724-4f17-81d5-f3b39f52f3c1.png">

2022-08-25 14:01 UTC, vechicin commented on styles.css
> +  }
Please make sure you match the template design.

<img width="658" alt="Screen Shot 2022-08-25 at 8 54 41" src="https://user-images.githubusercontent.com/82426682/186683816-03de0353-5c24-4ba2-a29a-268c25b23f0b.png">

<img width="430" alt="Screen Shot 2022-08-25 at 8 54 56" src="https://user-images.githubusercontent.com/82426682/186683883-e0c8bca7-7a41-4926-aab5-a779a989b69c.png">

2022-08-26 08:09 UTC, Abe1able commented on styles.css
> +@media screen and (min-width: 995px) {
Thank you, fixed.

2022-08-26 08:33 UTC, Abe1able commented on styles.css
>    align-items: center;
Thank you, fixed.

2022-08-26 09:24 UTC, phelian23 approved these changes
Hi @Abe1able,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 12:33 UTC, merged